prgrms-web-devcourse-final-project/WEB2_3_Wooamo_FE

- src/app/(with-admin-header)/admin/AdminHeader.tsx
- src/app/(with-admin-header)/admin/AdminSidebar.tsx
- src/app/(with-admin-header)/admin/PartyList.tsx
- src/app/(with-admin-header)/admin/PaymentList.tsx
- src/app/(with-admin-header)/admin/layout.tsx
- src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
- src/app/(with-admin-header)/admin/manage/event/EventItem.tsx
- src/app/(with-admin-header)/admin/manage/event/page.tsx
- src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
- src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
- src/app/(with-admin-header)/admin/manage/item/page.tsx
- src/app/(with-admin-header)/admin/manage/party/[id]/CertificationDate.tsx
- src/app/(with-admin-header)/admin/manage/party/[id]/ParticipantItem.tsx
- src/app/(with-admin-header)/admin/manage/party/[id]/page.tsx
- src/app/(with-admin-header)/admin/manage/party/page.tsx
- src/app/(with-admin-header)/admin/page.tsx
- src/components/common/Modal.tsx
`style/publishing-admin-page` -> `dev`
관리자 페이지 전체 퍼블리싱
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#11
> [STYLE] 관리자 페이지 퍼블리싱

- src/app/(with-main-header)/AfterLoginHome.tsx
- src/app/(with-main-header)/BeforeLoginHome.tsx
- src/app/(with-main-header)/Timer.tsx
- src/app/(with-main-header)/TimerCategory.tsx
- src/app/(with-main-header)/TimerList.tsx
- src/app/(with-main-header)/TodoItem.tsx
- src/app/(with-main-header)/TodoList.tsx
- src/app/(with-main-header)/UserCard.tsx
- src/app/(with-main-header)/page.tsx
`style/publishing-after-login-mainpage` -> `dev`
로그인 후의 메인페이지 퍼블리싱(데스크탑 사이즈)
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#14
> [STYLE] 로그인 후 메인페이지 데스크탑 퍼블리싱

- src/app/(with-main-header)/AfterLoginHome.tsx
- src/app/(with-main-header)/BeforeLoginHome.tsx
- src/app/(with-main-header)/Timer.tsx
- src/app/(with-main-header)/TimerCategory.tsx
- src/app/(with-main-header)/TimerList.tsx
- src/app/(with-main-header)/TodoItem.tsx
- src/app/(with-main-header)/TodoList.tsx
- src/app/(with-main-header)/UserCard.tsx
`style/apply-mobile-login-home` -> `dev`
#20
> 💄 홈(로그인 후) 반응형 적용

- env.d.ts
- src/api/user/user.ts
- src/api/user/user.type.ts
`feat/signup` -> `dev`
API Request + Response 타입 설정 샘플 추가
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [CHORE] API Request + Response 타입 설정 샘플 추가

- next.config.ts
- src/api/admin/admin.ts
- src/api/admin/admin.type.ts
- src/app/(with-admin-header)/admin/PartyList.tsx
- src/app/(with-admin-header)/admin/PaymentList.tsx
- src/app/(with-admin-header)/admin/manage/party/page.tsx
- src/app/(with-admin-header)/admin/page.tsx
`feature/admin-mainpage` -> `dev`
어드민 메인 페이지 데이터 패칭
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
- 현재 목 서버이기 때문에 이미지는 백엔드 측에서 임시로 업로드 된 이미지가 출력됩니다
#23
> [FEAT] 어드민 메인 페이지

- src/api/auth/auth.ts
- src/api/auth/auth.type.ts
- src/api/common.type.ts
- src/api/user/user.type.ts
- src/app/(with-auth-header)/signup/page.tsx
- src/assets/css/globals.css
- src/hooks/useInputValidation.ts
`feat/signup` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#24
> [FEAT] 회원가입 기능 구현

- src/api/timer/timer.ts
- src/api/timer/timer.type.ts
- src/api/todo/todo.ts
- src/api/todo/todo.type.ts
- src/api/user/user.ts
- src/api/user/user.type.ts
- src/app/(with-main-header)/AfterLoginHome.tsx
- src/app/(with-main-header)/BeforeLoginHome.tsx
- src/app/(with-main-header)/TodoItem.tsx
- src/app/(with-main-header)/TodoList.tsx
- src/app/(with-main-header)/UserCard.tsx
- src/app/(with-main-header)/page.tsx
- src/components/common/Character.tsx
- src/components/common/Dropdown.tsx
- src/components/common/NotificationList.tsx
- src/store/todoStore.ts
`feat/home-without-timer` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
---
#36
> [FEAT] 홈 페이지 기능 구현 (타이머 제외)

- src/app/(with-main-header)/DesktopHeader.tsx
- src/components/common/Dropdown.tsx
`feat/logout` -> `dev`
로그아웃 기능 구현
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#40
> [FEAT] 로그아웃 기능 구현

- next.config.ts
- src/api/admin/admin.ts
- src/api/admin/admin.type.ts
- src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
- src/app/(with-admin-header)/admin/manage/event/EventItem.tsx
- src/app/(with-admin-header)/admin/manage/event/page.tsx
- src/app/actions.ts
- src/components/common/Modal.tsx
- src/components/ui/popover.tsx
`feat/admin-event-managementpage` -> `dev`
관리자 페이지의 이벤트 페이지 추가
- 코드를 어떻게 해야 깔끔해보일까요?
#37
> [FEAT] 관리자 페이지 이벤트 페이지

- src/api/friend/friend.ts
- src/api/friend/friend.type.ts
- src/api/timer/timer.ts
- src/api/timer/timer.type.ts
- src/api/user/user.ts
- src/api/user/user.type.ts
- src/app/(with-main-header)/boards/PostItem.tsx
- src/app/(with-main-header)/mypage/ClosetTab.tsx
- src/app/(with-main-header)/mypage/MyProfile.tsx
- src/app/(with-main-header)/mypage/ProfileEditButton.tsx
- src/app/(with-main-header)/users/[id]/PostsByUser.tsx
- src/app/(with-main-header)/users/[id]/StudyTimeJandy.tsx
- src/components/common/Avatar.tsx
`feat/mypage-without-studytime` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#42
> [FEAT] 마이페이지 기능 구현 (공부 시간 제외)

- src/api/admin/admin.ts
- src/api/admin/admin.type.ts
- src/api/shop/shop.ts
- src/api/shop/shop.type.ts
- src/app/(with-admin-header)/admin/manage/event/AddEvent.tsx
- src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
- src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
- src/app/(with-admin-header)/admin/manage/item/page.tsx
`feat/admin-item-managementpage` -> `dev`
어드민 페이지의 아이템 관리 페이지 기능 구현
- 지금 Mock 서버여서 변경 사항을 확인하기가 어렵습니다. 따라서 CostumeItem 컴포넌트에 아이템 '수정' 기능이 잘 구현된지 모르겠으니 수정 로직을 한 번 꼼꼼히 봐주세요!
#27
> [FEAT] 어드민 페이지 아이템 관리 페이지

- src/api/friend/friend.ts
- src/api/friend/friend.type.ts
- src/app/(with-main-header)/friends/FriendsItem.tsx
- src/app/(with-main-header)/friends/FriendsRequestItem.tsx
- src/app/(with-main-header)/friends/add/SearchedUserItem.tsx
- src/app/(with-main-header)/friends/add/page.tsx
- src/app/(with-main-header)/friends/page.tsx
- src/components/common/ProfileSummary.tsx
`feat/friends` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#47
> [FEAT] 친구 페이지 기능 구현

- env.d.ts
- package.json
- pnpm-lock.yaml
- src/api/shop/shop.ts
- src/api/shop/shop.type.ts
- src/api/user/user.ts
- src/app/(with-main-header)/shop/ChargeButton.tsx
- src/app/(with-main-header)/shop/RandomGatchaButton.tsx
- src/app/(with-main-header)/shop/ShopCostumeItem.tsx
- src/app/(with-main-header)/shop/page.tsx
`feat/shop-page` -> `dev`
상점 페이지 기능 구현
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
15" src="https://github.com/user-attachments/assets/dfff2b53-6a8d-4945-a8f5-2e0dbf361815" />
#53
> [FEAT] 상점 페이지

- .github/workflows/deploy.yml
` chore/create-deploy.yml` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [CHORE] CI/CD 템플릿 추가

- src/api/board/board.ts
- src/api/board/board.type.ts
- src/app/(with-main-header)/boards/[id]/Comment.tsx
- src/app/(with-main-header)/boards/[id]/Comments.tsx
- src/app/(with-main-header)/boards/[id]/Post.tsx
- src/app/(with-main-header)/boards/[id]/PostDeleteButton.tsx
- src/app/(with-main-header)/boards/[id]/page.tsx
- src/app/(with-main-header)/boards/[id]/update/page.tsx
- src/app/(with-main-header)/boards/create/page.tsx
`feat/board-create` -> `dev`
#52
> [Feat] 게시판 상세, 수정 페이지 기능구현

- env.d.ts
- src/api/party/party.ts
- src/api/party/party.type.ts
- src/app/(with-main-header)/party/ClosedParties.tsx
- src/app/(with-main-header)/party/ClosedPartyItem.tsx
- src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
- src/app/(with-main-header)/party/EventParties.tsx
- src/app/(with-main-header)/party/OngoingParties.tsx
- src/app/(with-main-header)/party/PartyItem.tsx
- src/app/(with-main-header)/party/PersonalQuest.tsx
- src/app/(with-main-header)/party/UpcomingParties.tsx
- src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
- src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
- src/app/(with-main-header)/party/[id]/page.tsx
- src/app/(with-main-header)/party/all/page.tsx
- src/app/(with-main-header)/party/create/CreatePartyButton.tsx
- src/app/(with-main-header)/party/create/page.tsx
- src/app/(with-main-header)/party/page.tsx
- src/components/common/ProfileSummary.tsx
- src/hooks/useDebounce.ts
`feat/party-page` -> `dev`
팟 페이지 기능 구현
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#58
> [FEAT] 팟 페이지

- src/api/admin/admin.ts
- src/api/admin/admin.type.ts
- src/api/shop/shop.ts
- src/api/shop/shop.type.ts
- src/app/(with-admin-header)/admin/PartyList.tsx
- src/app/(with-admin-header)/admin/manage/party/page.tsx
- src/app/(with-main-header)/shop/ShopCostumeItem.tsx
- src/app/(with-main-header)/shop/page.tsx
`feat/develop-function-productionServer` -> `dev`
실서버로 변경하면서 수정된 사항이나 목 서버로 연결하고 확인하지 못했던 기능을 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [FEAT] 실서버로 개발 중 수정사항

- src/api/board/board.ts
- src/api/fetchCustom.ts
- src/app/(with-main-header)/boards/create/page.tsx
`feat/board-search` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [FIX]board search 작업중 content-type 수정

- src/api/common.type.ts
- src/api/fetchCustom.ts
- src/api/friend/friend.ts
- src/app/(with-main-header)/DesktopHeader.tsx
- src/app/(with-main-header)/MobileHeader.tsx
- src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
- src/app/(with-main-header)/friends/add/SearchedUsers.tsx
- src/app/(with-main-header)/friends/add/page.tsx
- src/app/(with-main-header)/friends/page.tsx
- src/app/(with-main-header)/header.tsx
- src/app/(with-main-header)/layout.tsx
- src/hooks/useIsMobile.ts
`feat/friend-final` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#93
> [FEAT] 친구 페이지 실서버 구현 (채팅 제외)

- src/api/board/board.ts
- src/app/(with-main-header)/boards/[id]/Post.tsx
- src/app/(with-main-header)/boards/[id]/update/page.tsx
- src/app/(with-main-header)/boards/create/page.tsx
`feat/develop-board-productionServer` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#97
> ✨ [FEAT] 실서버로 게시글 작성, 수정, 삭제, 댓글 작성, 삭제 구현

- src/api/notification/notification.ts
- src/api/notification/notification.type.ts
- src/app/(with-main-header)/DesktopHeader.tsx
- src/app/(with-main-header)/MobileHeader.tsx
- src/components/common/NotificationList.tsx
- src/hooks/useNotification.ts
`feat/alarm-productionServer` -> `dev`
알림목록 실서버로 구현
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#107
> [Feat] 알림 목록 실서버 구현

- src/api/auth/auth.ts
- src/api/fetchCustom.ts
- src/middleware.ts
`fix/login-401-bug` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#114
> 🐛 로그인 - 401 에러 버그 수정

- .gitignore
- package.json
- src/api/auth/auth.ts
- src/api/fetchCustom.ts
- src/api/user/user.type.ts
- src/app/(with-auth-header)/signin/page.tsx
- src/app/(with-main-header)/mypage/ClosetTab.tsx
`feat/apply-https` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#120
> [FEAT] localhost에 https 적용

- src/api/party/party.ts
- src/app/(with-main-header)/party/EventParties.tsx
- src/app/(with-main-header)/party/PartyItem.tsx
- src/app/(with-main-header)/party/PersonalQuest.tsx
- src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
- src/app/(with-main-header)/party/[id]/page.tsx
- src/app/(with-main-header)/party/all/page.tsx
- src/app/(with-main-header)/party/create/CreatePartyButton.tsx
- src/app/(with-main-header)/party/page.tsx
`feat/partypage-bug` -> `dev`
- 팟 페이지 예외처리 및 버그 수정(일부 완료)
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#123
> [FIX] 팟 페이지 예외 처리 및 버그 수정(일부 완료)

- src/app/(with-main-header)/boards/BoardsHeader.tsx
- src/app/(with-main-header)/boards/PostImage.tsx
- src/app/(with-main-header)/boards/PostItem.tsx
- src/app/(with-main-header)/boards/[id]/Post.tsx
- src/app/(with-main-header)/boards/page.tsx
`fix/board-productionServer` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#115
> [Fix] 게시판 페이지 버그 수정

- src/api/party/party.ts
- src/app/(with-main-header)/party/EventParties.tsx
- src/app/(with-main-header)/party/PartyItem.tsx
- src/app/(with-main-header)/party/PersonalQuest.tsx
- src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
- src/app/(with-main-header)/party/[id]/page.tsx
- src/app/(with-main-header)/party/all/page.tsx
- src/app/(with-main-header)/party/create/CreatePartyButton.tsx
- src/app/(with-main-header)/party/page.tsx
`feat/partypage-bug` -> `dev`
팟 페이지 중복인증 버그 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#123
> [FIX] 팟 페이지 중복인증 버그 수정

- src/app/(with-main-header)/TimerItem.tsx
- src/store/timerStore.ts
`fix/timer-bug` -> `dev`
- 타이머가 자동저장이 되지 않는 오류 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#127
> [FIX] 타이머 자동저장 오류 수정

- src/api/party/party.ts
- src/api/shop/shop.ts
- src/api/timer/timer.ts
- src/api/user/user.ts
- src/app/(with-admin-header)/admin/manage/item/AddCustume.tsx
- src/app/(with-admin-header)/admin/manage/item/CostumeItem.tsx
- src/app/(with-main-header)/TimerCategory.tsx
- src/app/(with-main-header)/TimerItem.tsx
- src/app/(with-main-header)/party/ClosedPartyRewardButton.tsx
- src/app/(with-main-header)/party/PartyItem.tsx
- src/app/(with-main-header)/party/PersonalQuest.tsx
- src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
- src/app/(with-main-header)/party/[id]/ParticipateButton.tsx
- src/app/(with-main-header)/party/all/page.tsx
- src/app/(with-main-header)/party/create/CreatePartyButton.tsx
- src/app/(with-main-header)/shop/ChargeButton.tsx
`feat/update-add-revalidateTag` -> `dev`
- revalidateTag 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#134
> [FEAT] revalidateTag 수정

- src/app/(with-main-header)/party/PartyItem.tsx
- src/app/(with-main-header)/party/all/PartyItems.tsx
- src/app/(with-main-header)/party/all/page.tsx
- src/app/(with-main-header)/shop/ChargeButton.tsx
`fix/exceptionHandling-applySkeleton` -> `dev`
- 팟 검색 시 스켈레톤이 적용되지 않던 문제 수정
- 토스 결제 중 사용자가 취소할 시 에러 핸들링
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#138
> [FIX] 팟 검색 스켈레톤 적용 및 토스 결제 에러 핸들링

- src/api/party/party.ts
- src/api/user/user.ts
- src/app/(with-admin-header)/admin/AdminHeader.tsx
- src/app/(with-main-header)/party/EventParties.tsx
- src/app/(with-main-header)/party/[id]/page.tsx
- src/app/(with-main-header)/shop/RandomGatchaButton.tsx
- src/app/(with-main-header)/shop/ShopCostumeItem.tsx
- src/app/(with-main-header)/shop/page.tsx
- src/components/common/Input.tsx
`fix/bugs` -> `dev`
- 자잘한 버그 수정 및 기능 추가
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [FIX] 버그 수정

- env.d.ts
- src/api/chatting/chatting.ts
- src/api/friend/friend.ts
- src/app/(with-main-header)/chatting/ChattingInput.tsx
- src/app/(with-main-header)/chatting/ChattingItem.tsx
- src/app/(with-main-header)/friends/[id]/page.tsx
- src/app/(with-main-header)/friends/page.tsx
- src/app/(with-main-header)/mypage/ClosetTab.tsx
- src/app/(with-main-header)/mypage/page.tsx
- src/app/api/kakaoLogin/route.ts
- src/hooks/useInfiniteChatting.ts
- src/middleware.ts
`fix/chatting-bug` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#150
> [FIX] 채팅 버그 수정 및 옷장 레이아웃 수정

- src/app/(with-main-header)/DesktopHeader.tsx
- src/app/(with-main-header)/MobileHeader.tsx
- src/app/(with-main-header)/boards/PostItem.tsx
- src/components/common/NotificationList.tsx
- src/hooks/useNewNotification.ts
`fix/notificationList-productionServer` -> `dev`
알림목록 버그 수정, 애니메이션 추가
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#152
> [Fix] 알림 목록 실서버 버그 수정

- src/app/(with-main-header)/MobileHeader.tsx
- src/app/(with-main-header)/boards/PostImage.tsx
`fix/board-notification-final` -> `dev`
#173
> [Fix] 게시판/알림-최종 ui 수정

- src/app/(with-main-header)/party/[id]/page.tsx
`feat/error-correction` -> `dev`
- 팟 상세페이지 줄 바꿈 처리
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#176
> [FIX] 팟 상세페이지 줄 바꿈 처리

- src/app/(with-auth-header)/signin/page.tsx
- src/app/(with-main-header)/friends/add/FriendRequestButton.tsx
`delete/auto-login` -> `dev`
자동로그인 기능 제거 및 다른 사용자 프로필 보고 오류 수정
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [FIX] 자동로그인 수정 및 버그 수정

- src/api/board/board.ts
- src/api/user/user.ts
> [FIX] 게시판 revalidate 버그 2차 수정

- src/api/board/board.ts
- src/api/user/user.ts
- src/app/(with-main-header)/boards/[id]/page.tsx
> [FIX] 게시판 revalidate 버그 3차 수정

- src/app/(with-main-header)/DesktopHeader.tsx
- src/app/(with-main-header)/MobileHeader.tsx
> [FIX] 게시판 revalidate 버그 5차 수정

- src/api/board/board.ts
- src/app/(with-main-header)/DesktopHeader.tsx
- src/app/(with-main-header)/MobileHeader.tsx
- src/app/(with-main-header)/boards/PostInfo.tsx
- src/app/(with-main-header)/boards/PostItem.tsx
- src/app/(with-main-header)/boards/[id]/page.tsx
- src/utils/formatDateToTimeAgo.ts
`feat/` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
> [FIX] 게시판 revalidate 버그 6차 수정

- src/app/(with-main-header)/boards/PostItem.tsx
- src/app/(with-main-header)/boards/[id]/PostProfile.tsx
> [FIX] 게시글 revalidate 버그 수정

- src/app/(with-main-header)/boards/[id]/PostProfile.tsx
> [FIX] 게시글 revalidate 버그 최종 수정

- src/app/(with-main-header)/boards/[id]/Post.tsx
> 🐛 게시글 revalidate 버그 찐최종 수정

- src/app/(with-main-header)/boards/[id]/PostProfile.tsx
> [FIX] 게시글 revalidate 버그 찐찐최종 수정

- src/app/(with-main-header)/MobileHeader.tsx
- src/app/(with-main-header)/chatting/ChattingListItem.tsx
> 메인으로 파이널 배포

- src/app/(with-main-header)/party/[id]/AfterParticipateButtons.tsx
> [HOTFIX] 파티 - 인증 버그 수정

- src/app/(with-main-header)/MobileHeader.tsx
> [HOTFIX] 모바일 사이드바 - 로그아웃 버그 수정 2

- src/api/timer/timer.ts
`fix/month-studytime-bug` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#213
> [FIX] revalidate 시간이 잘못 지정되어있던 버그 수정

- src/app/(with-main-header)/party/[id]/page.tsx
`fix/cant-access-party-detail` -> `dev`
- PR 좀 봐주세요~~
- 어떻게 생각하시나요?
#216
> 🐛 파티 - 배포 시, 파티 상세 페이지에 접근할 수 없던 버그 수정
